remove ValidatingWebhookConfiguration for new ingress controller
* some of the pipelines which are now using the new ingress controller
  show errors like:
  Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.96.34.207:443: connect: connection refused
* these errors seem to be related to either a misconfiguration or a
  malfunctioning ingress-nginx admission webhook
* there is a lot of discussion online about this issue, but the
  solution seems to be largely dependent on the k8s version and the
  nginx-ingress installed and it might not be worth investigating a
  proper solution for the EOL kind version currently used
  https://stackoverflow.com/questions/61616203/nginx-ingress-controller-failed-calling-webhook
* the simple workaround for now is to just remove the validation webhook
  and defer the fix to the time when we upgrade and start using a
  maintained k8s and ingress-nginx version

Signed-off-by: Jan Klare <jan.klare@bisdn.de>
Change-Id: I5477597766f1b879e841f5e943a34684282cef1c